services:
  api:
    image: ghcr.io/willzeex/peladapay-api:latest
    container_name: peladapay-api
    restart: always

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:8080

    networks:
      - traefik-network
      - internal

    labels:
      - "traefik.enable=true"

      # router
      - "traefik.http.routers.peladapay-api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.peladapay-api.entrypoints=web"

      # service
      - "traefik.http.services.peladapay-api.loadbalancer.server.port=8080"

      # importante quando existem múltiplas redes
      - "traefik.docker.network=traefik-network"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    container_name: peladapay-db
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
  traefik-network:
    external: true