@host=http://localhost:8080
@sessionId=00000000-0000-0000-0000-000000000000

### Criar conta
POST {{host}}/api/users/account
Content-Type: application/json

{
  "fullName": "Wilkes Santos",
  "cpf": "08484206670",
  "whatsapp": "31993776059",
  "phone": "31993776059",
  "cellphone": "31993776059",
  "email": "will_kilsen@hotmail.com",
  "password": "Will@2025"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "will_kilsen@hotmail.com",
  "password": "Will@2025"
}
